project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - software.qmd
  resources:
    - CNAME
    - .nojekyll
    - slides/*.pdf
    - class-setup/dist/*.zip

website:
  title: ""
  search: false
  navbar:
    search: false
    title: MGMT 675
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Slides
      - href: software.qmd
        text: Software
    
format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true

comments:
  hypothesis: true
    
   



