project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - assignments.qmd
    - index-pdf.qmd
  resources:
    - CNAME
    - .nojekyll
    - slides/*.pdf
    - files/*.zip
    - files/*.xlsx
    - index-pdf.pdf
    - 1A.pdf
    - 1B.pdf
    - 1C.pdf
    - 2A.pdf
    - 2B.pdf
    - 2C.pdf
    - 3A.pdf
    - 3B.pdf
    - 3C.pdf
    - 3D.pdf
    - 4A.pdf
    - 4B.pdf
    - 4C.pdf
    - 5A.pdf
    - 5B.pdf
    - 5C.pdf
    - 6A.pdf
    - 6B.pdf

website:
  title: ""
  search: false
  navbar:
    search: false
    title: MGMT 675
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Slides
      - href: assignments.qmd
        text: Assignments

format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true

comments:
  hypothesis: true
