project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - assignments.qmd
    - files.qmd
    - software.qmd
    - index-pdf.qmd
    - exercises.qmd
    - assignment1.qmd
    - assignment2.qmd
    - assignment3.qmd
    - assignment4.qmd
    - assignment5.qmd
    - assignment6.qmd
  resources:
    - CNAME
    - .nojekyll
    - slides/*.pdf
    - class-setup/dist/*.zip
    - files/*
    - index-pdf.pdf
    - exercises.pdf
    - assignment1.pdf
    - assignment2.pdf
    - assignment3.pdf
    - assignment4.pdf
    - assignment5.pdf
    - assignment6.pdf

website:
  title: ""
  search: false
  navbar:
    search: false
    title: MGMT 675
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Slides
      - href: assignments.qmd
        text: Assignments
      - href: files.qmd
        text: Files
      - href: software.qmd
        text: Software
    
format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true

comments:
  hypothesis: true
    
   



